### ISSUE TITLE
Remove the extra left sidebar tray, move towards modals

### ISSUE THREAD

**Issue by jtaylorchang** [actually-colab/desktop#468]
This will increase the horizontal space available for the header as well as the main notebook content as well as simplifying our UI.

- [x] #450 Move kernel panel into the kernel selector
- [x] #473 Move the launch button into the kernel selector
- [x] #474 Remove the users panel entirely (until it is determined we want it again)
- [x] #475 Move profile to top right corner of header
- [ ] #476 Have settings be on the profile popup
